### ISSUE TITLE
Tracking issue for MailChimping the easy button.

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#1041]
Finally getting to this after a long week:
- [x]  Configure import
- [x]  Configure new MC tag
- [x]  Configure new MC buttons (traffic-light colors)
- [x]  Attempt a dummy-update through MC
- [x]  Attempt a dummy-removal through MC
- [x]  Rewrite MC copy
- [x]  Load test batch
- [x]  Schedule test batch for deployment

**Comment by 4kbt** [comment]
It's working like a boss. So good. Thank you @awong-dev !
