### ISSUE TITLE
I18N Launch Issue

### ISSUE THREAD

**Issue by awong-dev** [findthemasks/findthemasks#301]
## GENERAL

- [x] Bottom Nav w/ Country & Locale selectors in PROD
- [x] "state" filters work for French and Canada Provinces / Départements

## FRANCE

 - [x] https://findthemasks.com/data-fr.json is publishing
 - [x] https://findthemasks.com/fr/ is rendering
 - [x] Index.html localized to `fr-FR`
 - [ ] Localization has signed off on index.html for `fr-FR`
 - [ ] Localization has signed off on Google Form for France
 - [ ] Data moderation lead identified for France
 - [ ] Social media / advertisement leader identified for France
 - [x] Map centers on France
 - [ ] AppScript for geocoding entries attached to intake form.

## CANADA

**Phase 1**
 - [x] https://findthemasks.com/data-ca.json is publishing
 - [x] https://findthemasks.com/ca/ is rendering
 - [ ] Index.html localized to `en-CA` (remove "america's" reference)
 - [ ] Index.html localized to `fr-CA` (can just use fr-fr initially)
 - [x] Localization has signed off on Google Form for Canada (in en-CA)
 - [ ] Data moderation lead identified for Canada
 - [ ] Social media / advertisement leader identified for Canada
 - [x] Map centers on Canada
 - [ ] AppScript for geocoding entries attached to intake form.

**Phase 2**

  - [ ] Localization has signed off on Google Form including `fr-CA`

**Comment by nburt** [comment]
Adding broken state filters to the list: https://github.com/findthemasks/findthemasks/issues/304

**Comment by nburt** [comment]
@awong-dev can this be closed?

**Comment by saikatbhadra** [comment]
I am going to close this because I believe these are done. Please re-open if not
