### ISSUE TITLE
Start tracking user actions in google analytics

### ISSUE THREAD

**Issue by saikatbhadra** [findthemasks/findthemasks#317]
## Developer Story
As a developer I want to see which actions my users take.

## Acceptance Criteria (WIP)
An action in GA in generated when:

### Map actions

- [x] A user initiates a map search
- [x] A user clicks a state filter
- [x] A user clicks an equipment filter
- [x] A user resets the map
- [x] A user clicks on "use my location"

### i18n
- [x] A user changes country
- [x] A user changes language

**Comment by saikatbhadra** [comment]
Taking this issue on

**Comment by saikatbhadra** [comment]
Closing this issue as the major events are covered. If anyone wants more GA events please open a new issue
