### ISSUE TITLE
Vnext prelaunch checklist

### ISSUE THREAD

**Issue by awong-dev** [findthemasks/findthemasks#48]
- [ ] Ensure a change in form data percolates
- [ ] Ensure the stylesheet is named something OTHER than style.css and style1.css to avoid month-long caching crazy
- [ ] Open incognito tab. Pop open web inspector and go to "networks" tab. Open the page. Check the Response headers for all of index.html, stylesheet, etc., and ensure that the cache-control max-age does not look insane.

**Comment by r-pop** [comment]
For list-locations.js I am seeing a worrisome cache setting:
```
cache-control: max-age=14400
cf-cache-status: EXPIRED
cf-ray: 577a3a046e2ffda1-PDX
content-encoding: br
content-type: application/javascript
date: Sat, 21 Mar 2020 19:54:46 GMT
etag: W/"1f65-5a1623f3c9254-gzip"
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
expires: Sat, 21 Mar 2020 19:59:46 GMT
last-modified: Sat, 21 Mar 2020 19:17:03 GMT
server: cloudflare
status: 200
vary: Accept-Encoding,User-Agent
```

**Comment by r-pop** [comment]
Also I saw this in cloudflare: Note: By default, Cloudflare does not cache HTML content. You can create a Page Rule to cache static HTML content.

**Comment by r-pop** [comment]
Talked to Albert, this should all be fine

**Comment by awong-dev** [comment]
obsolete.
