### ISSUE TITLE
Data blog launch checklist

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#636]
- [x] Surface HTML for comments
- [x] Get sign-off from #comms on content
- [x] Get sign-off from #comms on author list
- [x] Solicit help from #dev on best way to bring it in as a PR. 
- [x] Get #ux  / #dev assistance on html style-sheets
- [x] Figure out how it might fit into V2 styling
- [x] Are Figures 3 and 4 degenerate? (@4kbt thinks not, but smarter people do)
- [x] Integrate Lee's changes
- [x] Integrate Detwiler's changes
- [x] Proofread / styling when integrated into site, but unlinked
- [x] Create permalink (blog/2021-04-21-Data-Insights)
- [x] Make facebook share-link reference permalink
- [x] Have a dev see if there's a way to make social-media links flow in through handlebars (optional)
- [x] Cross fingers that analysis is correct-enough.
- [ ] Release
- [ ] Go public, drive publicity.

**Comment by 4kbt** [comment]
Document surfaced here for comment: https://faculty.washington.edu/cah49/ftmResearchNote.html

**Comment by 4kbt** [comment]
Closing -- 'cause it's done!
