### ISSUE TITLE
Tracking issue for the greatest data-refresh in the history of FTM

### ISSUE THREAD

**Issue by 4kbt** [findthemasks/findthemasks#755]
Also, the only data-refresh ever attempted.

Many of these can be broken into their own Issues as we go.

- [ ] Assess the number of remaining cells in Sheets. (#776)
- [ ] Are there non-lead moderators who might be willing to own the refresh process?
- [x] @4kbt , enable outbound gmailing as data@. 
- [x] Add expiration columns to Combined.
- [x] Add follow-up questions to the intake/update form.
- [x] Craft manual refresh email
- [x] Send manual emails
- [x] Estimate expected response/takedown rate
- [x] Create outbound repository address (#771)
- [x] Determine the right time of day to send refresh email (Strawman: 8 am Pacific, weekdays)
- [ ] Add Sheets dashboard entry to assess the number of entries that are 7, 14, 21, and 28-days stale.
- [x] Prototype a mail-merge (#770)
- [x] Test mail-merge in prod with dummy addresses (#773 )
- [ ] Round up enough moderators 
- [ ] Identify emails that we can from the early 1500 entries / Ethan's database. (#772) 
- [x] Launch emails in blocks of ~1-200 in order to keep the rate manageable as we learn/err. (#774 )
- [ ] Settle on expiration cycle (Strawman: warn at 14 days, warn again at 20 days, expire at 21) (#688)
- [ ] Refresh all the entries.
- [ ] Make refreshing an automated continuous process. (#775)
- [ ] Win.

**Comment by 4kbt** [comment]
This is basically done. I don't think adding an automation step is likely/practical.
